### ISSUE TITLE
Can I upload to "glacier" vault using vertx-s3-client ?

### ISSUE THREAD

**Issue by jinho-scenappsm** [hubrick/vertx-s3-client#16]
Hi team.
This is maybe a stupid question, but can I upload files to aws glacier using this vertx-s3-client ?

Jinho

**Comment by eemmiirr** [comment]
@jinho-scenappsm No not really it's a totally different API. This is the glacier API http://docs.aws.amazon.com/amazonglacier/latest/dev/amazon-glacier-getting-started.html.
